version: '3'

services:
  sparnatural:
    build: .
    image: sparnatural:latest
    container_name: sparnatural
    volumes:
      - ./:/usr/src/app/
    restart: unless-stopped
    ports:
      - 8080:8080


